import fs from "node:fs";
import path from "node:path";
import sanitizeHtml from "sanitize-html";

export type Article = {slug:string;title:string;excerpt:string;category:string;date:string;publishedAt:string;modifiedAt:string;image:string;imageAlt?:string;source:string;lead:string;body:string[];takeaways:string[];contentHtml?:string;wordpressId?:number;originalUrl?:string};
const decodeSlug=(slug:string)=>{try{return decodeURIComponent(slug)}catch{return slug}};

const fallbackArticles: Article[] = [
  {slug:"legal-software-selection-checklist",title:"چک‌لیست انتخاب سامانه مدیریت امور حقوقی سازمان",excerpt:"هفت معیار عملی برای ارزیابی امنیت، گردش کار، گزارش‌گیری و قابلیت استقرار یک سامانه حقوقی سازمانی.",category:"راهنمای خرید",date:"۲۵ مرداد ۱۴۰۵",publishedAt:"2026-08-16",modifiedAt:"2026-08-16",image:"/news/software-selection.svg",source:"تحریریه رایان بارای",lead:"انتخاب سامانه حقوقی با فهرست بلند قابلیت‌ها آغاز نمی‌شود؛ نقطه شروع، شناخت فرآیندها، ریسک‌ها و معیارهای قابل سنجش سازمان است.",body:["پیش از مشاهده دمو، مسیر واقعی یک پرونده را از ثبت تا بایگانی ترسیم کنید. نقش‌ها، نقاط تصمیم، مهلت‌ها و اسنادی را که بین واحدها جابه‌جا می‌شوند مشخص کنید تا ارزیابی محصول بر اساس سناریوی واقعی انجام شود.","امنیت را به عبارت‌های کلی محدود نکنید. درباره سطح دسترسی مبتنی بر نقش، ثبت رویدادها، نسخه پشتیبان، محل نگهداری داده و نحوه خروج اطلاعات در پایان قرارداد پرسش‌های دقیق مطرح کنید.","گزارش‌گیری زمانی ارزشمند است که داده در نقطه انجام کار و با قواعد مشخص ثبت شود. در جلسه معرفی، ساخت یک گزارش مدیریتی واقعی و ردیابی آن تا پرونده مبنا را آزمایش کنید.","در نهایت، هزینه کل مالکیت را بسنجید: استقرار، آموزش، سفارشی‌سازی، پشتیبانی، ارتقا و یکپارچه‌سازی با سامانه‌های موجود باید در تصمیم نهایی دیده شوند."],takeaways:["ارزیابی با سناریوی واقعی سازمان، نه دموهای عمومی","کنترل دسترسی، تاریخچه تغییرات و امکان خروج داده","سنجش هزینه کل مالکیت و کیفیت پشتیبانی"]},
  {slug:"legal-data-migration-roadmap",title:"نقشه راه مهاجرت امن داده‌های حقوقی از فایل و اکسل",excerpt:"چگونه پرونده‌ها، اسناد و سوابق حقوقی را بدون از دست‌رفتن زمینه، مالکیت و قابلیت پیگیری منتقل کنیم؟",category:"تحول دیجیتال",date:"۲۲ مرداد ۱۴۰۵",publishedAt:"2026-08-13",modifiedAt:"2026-08-16",image:"/news/data-migration.svg",source:"مرکز دانش رایان بارای",lead:"مهاجرت داده فقط انتقال فایل نیست؛ باید ارتباط میان پرونده، اشخاص، اسناد، رویدادها، مسئول اقدام و مهلت‌ها نیز حفظ شود.",body:["کار را با فهرست منابع داده آغاز کنید: فایل‌های اکسل، پوشه‌های اشتراکی، سامانه‌های قدیمی، ایمیل‌ها و بایگانی فیزیکی. برای هر منبع، مالک داده، کیفیت، محرمانگی و دوره نگهداری را ثبت کنید.","پیش از ورود داده، واژگان و ساختار مشترک بسازید. نام‌گذاری واحد برای نوع پرونده، مرجع رسیدگی، وضعیت، طرف دعوا و نتیجه، از تولید گزارش‌های متناقض جلوگیری می‌کند.","مهاجرت آزمایشی را روی یک مجموعه محدود اما نماینده اجرا کنید. تعداد رکوردها، پیوند اسناد، تاریخ‌ها و سطح دسترسی را با منبع تطبیق دهید و خطاها را پیش از انتقال گسترده اصلاح کنید.","پس از تأیید، انتقال مرحله‌ای و قابل بازگشت انجام دهید. صورت‌جلسه تطبیق، نسخه پشتیبان و مسئول تأیید هر مرحله باید بخشی از برنامه مهاجرت باشد."],takeaways:["فهرست‌برداری و تعیین مالک هر منبع داده","پاک‌سازی و استانداردسازی پیش از انتقال","مهاجرت آزمایشی، تطبیق و برنامه بازگشت"]},
  {slug:"ai-legal-operations",title:"هوش مصنوعی چگونه عملیات حقوقی سازمان را تغییر می‌دهد؟",excerpt:"از خلاصه‌سازی اسناد تا کنترل ریسک؛ نقشه‌ای عملی برای استفاده مسئولانه از هوش مصنوعی در واحد حقوقی.",category:"هوش مصنوعی حقوقی",date:"۱۰ مرداد ۱۴۰۵",publishedAt:"2026-08-01",modifiedAt:"2026-08-01",image:"/news/legal-ai.svg",source:"تحلیل تحریریه بارای",lead:"هوش مصنوعی زمانی برای واحد حقوقی ارزش می‌سازد که در دل فرآیندهای کنترل‌شده قرار بگیرد، نه به‌عنوان یک ابزار جداافتاده.",body:["کاربردهای کم‌ریسک مانند طبقه‌بندی اسناد، استخراج داده و ساخت خلاصه اولیه می‌توانند زمان کارهای تکراری را کاهش دهند.","برای تصمیم‌های حقوقی، کنترل انسانی، ثبت منبع، سطح دسترسی و گزارش‌پذیری باید از ابتدا در معماری سامانه دیده شود."],takeaways:["شروع از فرآیندهای پرتکرار و قابل اندازه‌گیری","حفظ بازبینی انسانی برای خروجی‌های حساس","ثبت منبع، نسخه و مسئول تأیید"]},
  {slug:"digital-justice-data",title:"عدالت دیجیتال بدون حاکمیت داده کامل نمی‌شود",excerpt:"چرا کیفیت داده، سطح دسترسی و ردپای تغییرات پیش‌نیاز هر تحول دیجیتال حقوقی است؟",category:"حاکمیت داده",date:"۸ مرداد ۱۴۰۵",publishedAt:"2026-07-30",modifiedAt:"2026-07-30",image:"/news/governance.svg",source:"مرکز دانش بارای",lead:"داده حقوقی حساس، چندلایه و زمان‌مند است؛ بنابراین دیجیتالی‌سازی آن فقط اسکن سند نیست.",body:["پرونده دیجیتال باید ارتباط میان اشخاص، اسناد، رویدادها، مسئول اقدام و موعدها را حفظ کند.","کنترل سطح دسترسی و تاریخچه تغییرات، اعتماد سازمان به سامانه و امکان پاسخ‌گویی را افزایش می‌دهد."],takeaways:["تعریف مالک داده","دسترسی مبتنی بر نقش","ثبت کامل رویدادها"]},
  {slug:"legal-workflow-automation",title:"۵ نشانه که گردش کار حقوقی سازمان نیاز به بازطراحی دارد",excerpt:"از موعدهای از‌دست‌رفته تا گزارش‌سازی دستی؛ نشانه‌هایی که هزینه پنهان ایجاد می‌کنند.",category:"اتوماسیون حقوقی",date:"۵ مرداد ۱۴۰۵",publishedAt:"2026-07-27",modifiedAt:"2026-07-27",image:"/news/integration.svg",source:"تحلیل تحریریه بارای",lead:"مشکل بسیاری از واحدهای حقوقی کمبود تلاش نیست؛ پراکندگی اطلاعات و نبود یک جریان کار مشترک است.",body:["اگر وضعیت پرونده فقط با تماس از کارشناس روشن می‌شود، داده عملیاتی در سامانه ثبت نشده است.","گردش کار استاندارد باید انعطاف‌پذیر باشد و در عین حال مسئولیت، موعد و مرحله هر اقدام را روشن نگه دارد."],takeaways:["اندازه‌گیری زمان چرخه","کاهش ورود دوباره اطلاعات","داشبورد مشترک برای مدیر و کارشناس"]},
  {slug:"municipal-commissions",title:"مدیریت دیجیتال کمیسیون‌های ماده ۳۸ و ۷۷",excerpt:"چطور پرونده، جلسه، رأی و پیگیری اجرا در یک زنجیره قابل ردیابی قرار می‌گیرند؟",category:"شهرداری و کمیسیون‌ها",date:"۲ مرداد ۱۴۰۵",publishedAt:"2026-07-24",modifiedAt:"2026-07-24",image:"/news/justice.svg",source:"مرکز دانش بارای",lead:"کمیسیون‌ها به بستری نیاز دارند که مسیر پرونده را از ثبت تا رأی و اجرا بدون گسست نگه دارد.",body:["ساختار پرونده باید مستندات، طرفین، جلسات، گردش ارجاع و تصمیم‌ها را یکپارچه کند.","گزارش‌های مدیریتی وقتی دقیق‌اند که اطلاعات در نقطه انجام کار و با قواعد اعتبارسنجی ثبت شوند."],takeaways:["تقویم جلسه و دستورکار","نسخه معتبر رأی و مستندات","پیگیری اجرای تصمیم"]}
];

const clean=(article:Article):Article=>({...article,slug:decodeSlug(article.slug),contentHtml:article.contentHtml?sanitizeHtml(article.contentHtml,{allowedTags:["p","h2","h3","h4","ul","ol","li","blockquote","strong","em","a","figure","figcaption","img","table","thead","tbody","tr","th","td","br","hr"],allowedAttributes:{a:["href","title","target","rel"],img:["src","alt","width","height","loading"],"*":["id"]},allowedSchemes:["http","https","mailto","tel"],transformTags:{a:sanitizeHtml.simpleTransform("a",{rel:"noopener noreferrer"},true),img:sanitizeHtml.simpleTransform("img",{loading:"lazy"},true)}}):undefined});
const loadSnapshot=():Article[]=>{try{const file=path.join(process.cwd(),"content/wordpress-posts.json");const parsed=JSON.parse(fs.readFileSync(file,"utf8"));return Array.isArray(parsed.posts)?parsed.posts.map(clean):[]}catch{return []}};
const snapshot=loadSnapshot();
export const articles:Article[]=(snapshot.length?snapshot:fallbackArticles).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));
export const contentMode=snapshot.length?"wordpress":"fallback";
export const getArticle = (slug:string) => {const normalized=decodeSlug(slug);return articles.find((article)=>decodeSlug(article.slug)===normalized)};
