import type {Metadata} from "next";
import Link from "next/link";
import {getProduct} from "@/lib/products";
import {site,jsonLd} from "@/lib/seo";

const product=getProduct("legal-management")!;
export const metadata:Metadata={title:product.title,description:product.description,alternates:{canonical:"/products/legal-management/"},openGraph:{title:product.title,description:product.description,type:"website"}};
export default function LegalManagement(){
  const faq=[{q:"سامانه جامع مدیریت امور حقوقی چیست؟",a:"بستری یکپارچه برای ثبت، پیگیری و گزارش‌گیری از پرونده‌ها، دعاوی، اسناد، جلسات، آرا و اقدامات حقوقی سازمان است."},{q:"آیا گردش کار متناسب با ساختار سازمان تنظیم می‌شود؟",a:"بله؛ نقش‌ها، فرم‌ها، وضعیت‌ها، مسیر ارجاع و گزارش‌ها براساس ساختار و فرآیند مصوب سازمان پیکربندی می‌شوند."},{q:"اطلاعات محرمانه چگونه کنترل می‌شوند؟",a:"سطح دسترسی مبتنی بر نقش، ثبت رویدادها، تاریخچه تغییرات و امکان استقرار در زیرساخت سازمان، چارچوب کنترل داده را فراهم می‌کند."}];
  const schema={"@context":"https://schema.org","@graph":[{"@type":"SoftwareApplication",name:product.title,applicationCategory:"BusinessApplication",operatingSystem:"Web / On-premise",description:product.description,provider:{"@type":"Organization",name:"رایان بارای",url:site.url},featureList:product.features},{"@type":"FAQPage",mainEntity:faq.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))}]};
  return <><section className="pageHero productPageHero"><div className="wrap"><nav className="breadcrumb" aria-label="مسیر صفحه"><Link href="/">خانه</Link><span>/</span><Link href="/#legal-suite">راهکارها</Link></nav><span className="kicker"><i/> {product.eyebrow}</span><h1>{product.title}</h1><p>{product.description}</p><div className="actions"><Link className="button" href="/#demo">درخواست دموی تخصصی ←</Link><Link className="button ghost" href="/#legal-suite">سبد راهکارهای حقوقی</Link></div></div></section>
  <section className="section productNarrative"><div className="wrap productNarrativeGrid"><div><span className="eyebrow">چرا این سامانه؟</span><h2>پرونده حقوقی، از پوشه پراکنده به جریان قابل کنترل</h2></div><p>{product.intro}</p></div></section>
  <section className="section soft"><div className="wrap"><header className="sectionHead"><div><span className="eyebrow">قابلیت‌های محوری</span><h2>دید ۳۶۰ درجه از امور حقوقی سازمان</h2></div><p>اطلاعات هر پرونده در کنار مسئول اقدام، مهلت، سند و سابقه تصمیم قرار می‌گیرد.</p></header><div className="capabilityGrid">{product.features.map((feature,index)=><article key={feature}><b>{String(index+1).padStart(2,"0")}</b><h3>{feature}</h3><p>طراحی‌شده برای کاهش کار دستی، روشن‌شدن مسئولیت و دسترسی سریع به سابقه هر اقدام.</p></article>)}</div></div></section>
  <section className="section workflowSection"><div className="wrap"><header className="sectionHead compactHead"><div><span className="eyebrow">مسیر کار</span><h2>از تشکیل پرونده تا اجرا و گزارش</h2></div></header><div className="productWorkflow">{product.workflow.map((step,index)=><article key={step}><b>{index+1}</b><h3>{step}</h3></article>)}</div><div className="outcomeRow">{product.outcomes.map(outcome=><span key={outcome}>✓ {outcome}</span>)}</div></div></section>
  <section className="section soft"><div className="wrap narrow"><header className="sectionHead"><div><span className="eyebrow">پرسش‌های متداول</span><h2>پیش از انتخاب سامانه</h2></div></header><div className="faq">{faq.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></div></section>
  <section className="consultCta"><div className="wrap consultCtaIn"><div><span>گام بعدی</span><h2>سامانه را با سناریوی واقعی سازمان خود ببینید.</h2><p>در جلسه تخصصی، نقش‌ها، داده‌ها، گردش کار و گزارش‌های مورد نیاز را مرور می‌کنیم.</p></div><Link className="button" href="/#demo">رزرو جلسه دمو ←</Link></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={jsonLd(schema)}/></>;}
